language: java
jdk:
- oraclejdk8
#deploy:
#  provider: heroku
#  api_key:
#    secure: etUFStU6AFCcB8I2nJtxrFJ/uj5rIUtmBwt7YhO8al3oCPwdbaiQsawL5G5g/KBUghJYahjIYQ+AdZHiaONDp7nRLd8JPCUxqrJCXDKtDSt9rqrlXpR2tHuddHzIhwLTjlXIorwZyHwX5uru/k67ak26gxhspte4EcoGoph/Vxk5AyIA68POvqgQsFt8ZSEaBFw3/n3PbRGoDYuAtXixXKEKlRbQhCGOtjWXm4PlvQGxmeE/39d1QvJEjc2bU5DPmnWDs0PoL8Yv4JqGTa6dnNus95kc7JgoOfM9w3GeHYqxvQMZRhneyDl5PeGecN4JIQYoZRsOnj6d8ZNeZ8vt1asiEGJrnby0mPp77UVFMEQHFREjkP8HdXB/NU5jxeqxmup4bnAzo0lOe/ijBSXJcUd5SL9QqS20yTageiaQPdM0py1zN42buWkFnEDe+WBu+QVj9ZiWi33XtevCzErHWJ0ujnA5xutcvcD1pBndNKtGPSYQFlIP2Sq4UONk7jzbn8PjtGYIsdBiCTbzw943D/ain+yjcOoYKo1So8v3U2DEza1hqwums4kOCGmJrpKmJlh4Be53ZGUQ2SbGYvM8jPodKQC2qm5RoRNRmOA3lFYMapBnhmZoEEd5m9wSeWdX+2a4MShW3DTEfhswwpJyhW9F/J7n2GBWrcwiBQcngaE=
#app: radiant-cliffs-35641
