language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: TTenVdSs0LHUct9R1i1ZF3/6KBUHb9d8nSoy1cgCaoo/yUngPDmKKsvdTuE7Eq4yTDm95rShITZzBSc1SpxA1Esqs0WTQjuJwll70V7yOx+O+gAqMx4qPHhdD7JTWLC/+LtDk0j0m8PKTTMDSkmPk95E9SZlC8kgjbnacQeaWWUFly8Y9KDuJJ2ieQE9lsRhy9rpztxCrBjkASiUCUHJKP85fHgkNOhMz9q5YHhbKi/OT6fIiMRu0uR+eRRfrK0ITPy+XBtufz3JczTylmTeqd6AFiWqMbEE6F5dzWLvKdjyrILiNssrtkpQ7DPrS9tPImesT4RbvIbev4FwY4LsJ8DmPjUAuGyQaTPoGnLsSbXF7Pe8Jym9iJgkpz4wr82ovz7w6pmkumPMr8KaFaWgoi4OC4ARRsyesLedfJSWuqXonRB9Ns1N92bjF2Y3ECGqTi09C3x3PirzmZpM5FCUdYs0DHVgJXYLvECNZKI4jta15OaMWMWHvV5gtcRkiWEjD4/IK/U/4YjBU5At3kjQ+ilQlxp/48y5/xlzHHaYYhMyDqJ4sf1Lc7hTFmGCXoFE8rLpFA9urqTD/CPVcEPkScx/XgUB5DDOV5umTsVjHoAdXZR2ROANrbbYEKwtLFkh3o6AyaGlNfJ9jNLTyIxM8z3m5JQlP5ic+mLtznxf7oo=
  app: myartbook
